Randomize port for udp/tcp tests
clj-commons/aleph pull request #661
Opened 2023-01-27 07:37 UTC by arnaudgeiser

## Description

This ensures port are randomized for udp and tcp servers.
It helps to stabilize the tests when some servers take a little bit of time to be shutdown.

2023-01-29 06:52 UTC, KingMob requested changes
This is a good idea, but the implementation isn't quite safe. Since `rand-port` closes the ServerSocket, the port becomes available again, and could be snapped up before we start the server.

I double-checked the docs, and if you pass 0 for `:port` to `start-server`, it will do what we want: find an unused port and grab it simultaneously.

2023-01-29 12:31 UTC, arnaudgeiser commented
Yes, definitely, it will work for the server.
But we need to be aware of the port used so it can be exercised by the client on the tests.
Do you have a proposition here?

2023-01-30 08:06 UTC, KingMob commented
The object returned from `start-server` implements the AlephServer protocol, which has a method `port`, which returns the port number.

2023-02-02 09:24 UTC, KingMob approved these changes

2023-02-02 09:45 UTC, merged